# frozen_string_literal: true

# This file is auto-generated by Jekyll Auth
# It tells Heroku how to launch our site

require "jekyll-auth"
jekyll_auth:
    ssl: true
destination: ./docs
run JekyllAuth.site
